---
  sudo: enabled

  services:
    - docker

  before_install:
    - sudo apt-get install -y curl
    - sudo curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose

  script:
    - docker-compose stop -t 0 && sudo rm -f ./data/
    - cp .env.example .env
    - sudo ./x-setup-server.sh
    - docker images
    - docker ps -a
    - CONFIGURATOR_OPTIONS=--debug docker-compose up -d
    - docker-compose logs -f configurator
    - exit $(docker inspect -f {{.State.ExitCode}} $(docker-compose ps -q configurator))
