---
  env:
    TESTS_IMAGE=test_image
    CONFIGURATOR_OPTIONS=--debug 

  sudo: enabled

  services:
    - docker

  before_install:
    - sudo apt-get install -y curl
    - sudo curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - docker build -t ${TESTS_IMAGE} -f tests/Dockerfile ./tests/

  script:
    - docker-compose stop -t 0 && sudo rm -f ./data/
    - cp .env.example .env
    - sudo ./x-setup-server.sh
    - docker images
    - docker ps -a
    - docker-compose up -d
    - docker-compose logs -f configurator
    - docker-compose exec server zabbix_get -s agent -k docker.discovery
    - docker-compose exec server zabbix_get -s agent -k web.discovery[http,2]
    - docker-compose exec server zabbix_get -s agent -k web.discovery[https,3]
    - exit $(docker inspect -f {{.State.ExitCode}} $(docker-compose ps -q configurator))
