---
  env:
    TESTS_IMAGE=test_image
    TESTS_CONTAINER_NAME=tests
    CONFIGURATOR_OPTIONS=--debug

  sudo: enabled

  services:
    - docker

  before_install:
    - sudo apt-get install -y curl
    - sudo curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose
    - docker build -t ${TESTS_IMAGE} -f tests/Dockerfile ./tests/

  script:
    - cp .env.example .env
    - docker-compose stop -t 0 && sudo rm -f ./data/
    - sudo ./x-setup-server.sh
    - docker images
    - docker ps -a
    - docker-compose up -d
    - docker-compose logs -f configurator
    - docker-compose exec server zabbix_get -s agent -k docker.discovery
    - docker-compose exec server zabbix_get -s agent -k web.discovery[http,2]
    - docker-compose exec server zabbix_get -s agent -k web.discovery[https,-1,--unique]
    - |
        docker run -d -h ${TESTS_CONTAINER_NAME} \
          --name ${TESTS_CONTAINER_NAME} \
          --env-file .env \
          --network $(docker inspect --format="{{range .NetworkSettings.Networks }}{{.NetworkID}}{{ end }}" $(docker-compose ps -q server)) \
          --link $(docker-compose ps -q frontend | cut -c1-12):$(grep ZBX_SERVER_NAME .env | cut -d "=" -f 2) \
          -v $(pwd):/project \
          -w /project \
          ${TESTS_IMAGE}
    - sleep 5
    - docker exec ${TESTS_CONTAINER_NAME} tests/testing.py || exit 1
    - exit $(docker inspect -f {{.State.ExitCode}} $(docker-compose ps -q configurator))
