---
  sudo: enabled

  language: python

  python:
    - "2.7"

  services:
    - docker

  before_install:
    - sudo apt-get install -y curl
    - sudo curl -L https://github.com/docker/compose/releases/download/1.17.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    - sudo chmod +x /usr/local/bin/docker-compose

  script:
    - sudo ./x-setup-server.sh
    - docker images
    - docker ps -a
    - CONFIGURATOR_OPTIONS=--skip-configure docker-compose up -d
    - CONFIGURATOR_OPTIONS=--debug docker-compose up --exit-code-from configurator --abort-on-container-exit configurator
