version: "3"
services:

  server:
    hostname: server
    image: zabbix/zabbix-server-mysql:ubuntu-${ZBX_VERSION:-3.4}-latest
    ports:
      - "${ZBX_EXTERNAL_SERVER_PORT:-10051}:10051"
    links:
      - db
      - smtp
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE:-zabbix}
      - MYSQL_USER=${MYSQL_USER:-zabbix}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-zabbix}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  frontend:
    hostname: frontend
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-${ZBX_VERSION:-3.4}-latest
    ports:
      - "${HTTP_BIND_ADDR:-0.0.0.0:80:80}"
    links:
      - server
      - db
    environment:
      - ZBX_SERVER_HOST=server
      - DB_SERVER_HOST=db
      - PHP_TZ=${PHP_TZ:-Europe/Kiev}
      - ZBX_SERVER_NAME=${ZBX_SERVER_NAME:-zabbix}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-zabbix}
      - MYSQL_USER=${MYSQL_USER:-zabbix}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-zabbix}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  db:
    hostname: db
    build:
      dockerfile: Dockerfile.database
      context: ./
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-zabbix}
      - MYSQL_USER=${MYSQL_USER:-zabbix}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-zabbix}
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  agent:
    hostname: agent
    build:
      dockerfile: Dockerfile.agent
      context: ./
      args:
        - ZBX_VERSION=${ZBX_VERSION:-3.4}
    privileged: true
    links:
      - server
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=server
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  smtp:
    hostname: smtp
    image: tianon/exim4
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"
