#
# MAINTAINER: devops@onix-systems.com
#

version: "3"
services:

  server:
    hostname: server
    image: zabbix/zabbix-server-mysql:ubuntu-${ZBX_VERSION:-3.4}-latest
    ports:
      - "${ZBX_EXTERNAL_SERVER_PORT:-10051}:10051"
    networks:
      zabbix_net:
        ipv4_address: ${SUBNET_PREFIX:-172.15.0.}254
    links:
      - db
      - smtp:smtp.local
    extra_hosts:
      - "agent:${SUBNET_PREFIX:-172.15.0.}1"
    environment:
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE:-zabbix}
      - MYSQL_USER=${MYSQL_USER:-zabbix}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-zabbix}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  frontend:
    hostname: frontend
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-${ZBX_VERSION:-3.4}-latest
    ports:
      - "${HTTP_BIND_ADDR:-0.0.0.0:80}:80"
    networks:
      - zabbix_net
    links:
      - server
      - db
    environment:
      - ZBX_SERVER_HOST=server
      - DB_SERVER_HOST=db
      - PHP_TZ=${PHP_TZ:-Europe/Kiev}
      - ZBX_SERVER_NAME=${ZBX_SERVER_NAME:-zabbix}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-zabbix}
      - MYSQL_USER=${MYSQL_USER:-zabbix}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-zabbix}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  db:
    hostname: db
    build:
      dockerfile: Dockerfile.database
      context: ./
    networks:
      - zabbix_net
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-zabbix}
      - MYSQL_USER=${MYSQL_USER:-zabbix}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-zabbix}
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  smtp:
    hostname: smtp
    image: tianon/exim4
    networks:
      - zabbix_net
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  configurator:
    hostname: configuration
    build:
      dockerfile: Dockerfile.configurator
      context: ./
    command: /configurator.py ${CONFIGURATOR_OPTIONS:- }
    volumes:
      - ./scripts/configurator.py:/configurator.py
    links:
      - frontend
      - db
    extra_hosts:
      - "agent:${SUBNET_PREFIX:-172.15.0.}1"
    networks:
      zabbix_net:
        ipv4_address: ${SUBNET_PREFIX:-172.15.0.}7
    environment:
      - ZBX_SERVER_URL=http://frontend
      - ZBX_ADMIN_PASSWORD=${ZBX_ADMIN_PASSWORD:-zabbix}
      - ZBX_DISABLE_GUEST=${ZBX_DISABLE_GUEST:-true}
      - ZBX_AGENT_HOSTNAME=${ZBX_AGENT_HOSTNAME:-agent}
      - SMTP_SERVER=smtp.local
      - SMTP_EMAIL=${SMTP_EMAIL:-monitor@smtp.local}
      - ADMIN_EMAIL_ADDRESS=${ADMIN_EMAIL_ADDRESS:-admin@smtp.local}
      - DEFAULT_HOST_SECRET=${DEFAULT_HOST_SECRET:- }
      - URL_LIST=${URL_LIST:- }
      - DB_SERVER_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE:-zabbix}
      - MYSQL_USER=${MYSQL_USER:-zabbix}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-zabbix}
      - ZBX_CONFIG=${ZBX_CONFIG:- }
      - ZBX_ADMIN_USERS=${ZBX_ADMIN_USERS:- }
networks:
  zabbix_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: ${SUBNET_PREFIX:-172.15.0.}0/24
